# version: 2
# jobs:
#  build:
#    machine: true
#    steps:
#      - checkout 

#      # build image
#      - run: |         
#          docker info
#          docker build -t reactclient -f Dockerfile .
#      # deploy the image
#      - run: |
#          docker  login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
#          docker tag reactclient registry.heroku.com/$HEROKU_APP_NAME/web
#          docker push registry.heroku.com/$HEROKU_APP_NAME/web                
#          curl https://cli-assets.heroku.com/install.sh | sh
#          heroku container:release web -a $HEROKU_APP_NAME

version: 2.1
orbs:
  heroku: circleci/heroku@1.0.0
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
      command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
      
